packages:
  - '.'
  - 'frontend'

catalogs:
  # 前端生产依赖
  prod:
    vue: ^3.5.13
    vue-router: ^4.5.0
    pinia: ^3.0.1
    naive-ui: ^2.41.0
    date-fns: ^4.1.0
    mitt: ^3.0.1

  # 开发工具
  dev:
    typescript: ^5.8.3
    vite: ^4.5.12
    vitest: ^1.2.2
    vue-tsc: ^2.2.8
    '@antfu/eslint-config': ^4.3.0
    '@antfu/ni': ^24.1.0
    simple-git-hooks: ^2.11.1
    lint-staged: ^15.4.3
    '@vitejs/plugin-vue': ^4.6.2
