// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function CallDeepSeekAPI(arg1:types.DeepSeekAPIRequest):Promise<types.DeepSeekAPIResponse>;

export function CompleteFocusSession(arg1:types.CompleteFocusSessionRequest):Promise<types.BasicResponse>;

export function CreateTodo(arg1:types.CreateTodoRequest):Promise<types.CreateTodoResponse>;

export function DeleteTodo(arg1:number):Promise<types.BasicResponse>;

export function GetAllTodos():Promise<Array<types.TodoItem>>;

export function GetDailySummary():Promise<types.DailySummaryResponse>;

export function GetEventStats(arg1:types.GetStatsRequest):Promise<types.EventStatsResponse>;

export function GetPomodoroStats(arg1:types.GetStatsRequest):Promise<types.PomodoroStatsResponse>;

export function GetStats(arg1:types.GetStatsRequest):Promise<Array<types.StatResponse>>;

export function GetStatsSummary():Promise<types.StatSummary>;

export function Greet(arg1:string):Promise<string>;

export function StartFocusSession(arg1:types.StartFocusSessionRequest):Promise<types.StartFocusSessionResponse>;

export function UpdateStats(arg1:string):Promise<types.BasicResponse>;

export function UpdateTodo(arg1:types.UpdateTodoRequest):Promise<types.BasicResponse>;

export function UpdateTodoStatus(arg1:types.UpdateTodoStatusRequest):Promise<types.BasicResponse>;
