// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CallDeepSeekAPI(arg1) {
  return window['go']['main']['App']['CallDeepSeekAPI'](arg1);
}

export function CompleteFocusSession(arg1) {
  return window['go']['main']['App']['CompleteFocusSession'](arg1);
}

export function CreateTodo(arg1) {
  return window['go']['main']['App']['CreateTodo'](arg1);
}

export function DeleteTodo(arg1) {
  return window['go']['main']['App']['DeleteTodo'](arg1);
}

export function GetAllTodos() {
  return window['go']['main']['App']['GetAllTodos']();
}

export function GetDailySummary() {
  return window['go']['main']['App']['GetDailySummary']();
}

export function GetEventStats(arg1) {
  return window['go']['main']['App']['GetEventStats'](arg1);
}

export function GetPomodoroStats(arg1) {
  return window['go']['main']['App']['GetPomodoroStats'](arg1);
}

export function GetStats(arg1) {
  return window['go']['main']['App']['GetStats'](arg1);
}

export function GetStatsSummary() {
  return window['go']['main']['App']['GetStatsSummary']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function StartFocusSession(arg1) {
  return window['go']['main']['App']['StartFocusSession'](arg1);
}

export function UpdateStats(arg1) {
  return window['go']['main']['App']['UpdateStats'](arg1);
}

export function UpdateTodo(arg1) {
  return window['go']['main']['App']['UpdateTodo'](arg1);
}

export function UpdateTodoStatus(arg1) {
  return window['go']['main']['App']['UpdateTodoStatus'](arg1);
}
